spring.application.name=deal

spring.datasource.url=jdbc:postgresql://localhost:5438/postgres
spring.datasource.username=postgres
spring.datasource.password=pgpwd4habr
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.liquibase.change-log= classpath:db/changelog/db.changelog-v1.xml

server.port=8081

spring.kafka.producer.bootstrap-servers=localhost:9092
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
logging.level.org.apache.kafka=INFO
logging.level.org.springframework.kafka=DEBUG
